### ISSUE TITLE
Small things

### ISSUE THREAD

**Issue by Felipefpl** [Dom-aka-Doke/Advanced-SNES-ROM-Utility#1]
Hi, thanks for making this tool for us, i came to know it in romhacking.net, i have reports/suggestions to help improve it:

1 - The tool takes some time to start, idk much about coding but i wonder if some optimization would be possible to make things faster.

2 - After i patch a game we expect the game to be patched but this only happens when we close the program and see the msg to save, no patching tool that i know does that. It would be better if the patch was applied right after the patching.

3 - Suggestion: compressing the tool with 7zip i reduced the size to 239 KB. ;)

**Comment by Dom-aka-Doke** [comment]
Thanks for leaving some feedback and questions!

Regarding to your points:

1 - I personally only had some lags when loading files from a network storage via UNC from NAS and when this was the last folder in access. Otherwise it might come from a faulty installation of .NET Framework or really weak / old hardware. Can you provide some event logs, if none of these points apply?

2 - Well, I would call this behaviour the "advanced" part of this tool. Every operation is done "In Memory" until you save your file manually. That's right and ment to be so by design. Most people I know like to do some operations after or before applying a patch, like adding / removing a header, fixing checksum, fixing internal ROM size etc. But if this tools' only task was applying patches, I totally would agree in this point ;-)

3 - *funmode on* In times of gigabit internet connection and terabyte hard drives I really can't comprehend this point. Yeah, I might take a higher level of compression next release. Will keep it in mind for timeslip people from the 80s surfig 2020s internet. *funmode off*

I really hope you enjoy using this tool! If you have further questions, please don't hesitate!
