### ISSUE TITLE
progress bar for loading ROM

### ISSUE THREAD

**Issue by jeffythedragonslayer** [Dom-aka-Doke/Advanced-SNES-ROM-Utility#8]
When loading a big ROM the tool hangs and the window cannot be dragged.  Can there be a progress bar?

**Comment by Dom-aka-Doke** [comment]
Hi Jeff,
thanks for beeing interested in this tool and trying to help improving it.
I guess you cloned a version that isn't ment to be released at the moment and is still in development.
The reason it is already published here were some problems I had with deleting an old branch, renaming the new one and Visual Studio also made some trouble...
Finding and removing SRAM checks is still very experimental and might be much slower than the algorithm for finding region locks, but allows more felxible and compact pattern (regular expressions). Because of this,
I'm planning to handle ROM scanning for removing region locks and sram checks in another way in future and also implement some progress bars.

**Comment by jeffythedragonslayer** [comment]
Sure let me know if you need any help!

**Comment by Dom-aka-Doke** [comment]
For indicating a long process is running, a wait cursor is now implemented.
I think this will be enough to let users know that the application is still alive.
